

#define PIN_HOTHOUSE_SW_1_UP 9
#define PIN_HOTHOUSE_SW_1_DOWN 10
#define PIN_HOTHOUSE_SW_2_UP 7
#define PIN_HOTHOUSE_SW_2_DOWN 8
#define PIN_HOTHOUSE_SW_3_UP 5
#define PIN_HOTHOUSE_SW_3_DOWN 6
#define PIN_HOTHOUSE_FSW_1 25
#define PIN_HOTHOUSE_FSW_2 26

#define PIN_HOTHOUSE_SWITCH_1 PIN_HOTHOUSE_SW_1_UP
#define PIN_HOTHOUSE_SWITCH_2 PIN_HOTHOUSE_SW_1_DOWN
#define PIN_HOTHOUSE_SWITCH_3 PIN_HOTHOUSE_SW_2_UP
#define PIN_HOTHOUSE_SWITCH_4 PIN_HOTHOUSE_SW_2_DOWN
#define PIN_HOTHOUSE_SWITCH_5 PIN_HOTHOUSE_SW_3_UP
#define PIN_HOTHOUSE_SWITCH_6 PIN_HOTHOUSE_SW_3_DOWN
#define PIN_HOTHOUSE_SWITCH_7 PIN_HOTHOUSE_FSW_1
#define PIN_HOTHOUSE_SWITCH_8 PIN_HOTHOUSE_FSW_2

#define PIN_HOTHOUSE_POT_1 A1
#define PIN_HOTHOUSE_POT_2 A2
#define PIN_HOTHOUSE_POT_3 A3
#define PIN_HOTHOUSE_POT_4 A4
#define PIN_HOTHOUSE_POT_5 A5
#define PIN_HOTHOUSE_POT_6 A6

#define PIN_HOTHOUSE_LED_1 22
#define PIN_HOTHOUSE_LED_2 23



