#define PIN_PETAL_SWITCH_1 8
#define PIN_PETAL_SWITCH_2 9
#define PIN_PETAL_SWITCH_3 10
#define PIN_PETAL_SWITCH_4 13
#define PIN_PETAL_SWITCH_5 25
#define PIN_PETAL_SWITCH_6 26
#define PIN_PETAL_SWITCH_7 7

#define PIN_PETAL_ENC_A 28
#define PIN_PETAL_ENC_B 27
#define PIN_PETAL_ENC_CLICK 14

#define PIN_PETAL_EXPRESSION 15
#define PIN_PETAL_POT_1 16
#define PIN_PETAL_POT_2 19
#define PIN_PETAL_POT_3 17
#define PIN_PETAL_POT_4 20
#define PIN_PETAL_POT_5 18
#define PIN_PETAL_POT_6 21