#define PIN_PATCH_ENC_CLICK 0
#define PIN_PATCH_ENC_B 11
#define PIN_PATCH_ENC_A 12

#define PIN_OLED_DC 9
#define PIN_OLED_RESET 30

#define PIN_PATCH_MIDI_OUT 13
#define PIN_PATCH_MIDI_IN 14

#define PIN_PATCH_GATE_OUT 17
#define PIN_PATCH_GATE_IN_1 20
#define PIN_PATCH_GATE_IN_2 19

#define PIN_PATCH_CTRL_1 A0
#define PIN_PATCH_CTRL_2 A1
#define PIN_PATCH_CTRL_3 A6
#define PIN_PATCH_CTRL_4 A3

#define PIN_PATCH_CV_1 23
#define PIN_PATCH_CV_2 22
