// these are only valid using the Patch SM variant
#ifdef ARDUINO_DAISY_PATCH_SM

//analog pins
#define PIN_PATCH_SM_CV_1 A0
#define PIN_PATCH_SM_CV_2 A1 
#define PIN_PATCH_SM_CV_3 A2
#define PIN_PATCH_SM_CV_4 A3
#define PIN_PATCH_SM_CV_5 A4
#define PIN_PATCH_SM_CV_6 A5
#define PIN_PATCH_SM_CV_7 A6
#define PIN_PATCH_SM_CV_8 A7
#define PIN_PATCH_SM_ADC_9 A8
#define PIN_PATCH_SM_ADC_10 A9
#define PIN_PATCH_SM_ADC_11 A10
#define PIN_PATCH_SM_ADC_12 A11

#define PIN_PATCH_SM_CV_OUT_1 A12
#define PIN_PATCH_SM_CV_OUT_2 A13

// digital pins
#define PIN_PATCH_SM_GATE_IN_1 PG13
#define PIN_PATCH_SM_GATE_IN_2 PG14

#define PIN_PATCH_SM_GATE_OUT_1 PC14
#define PIN_PATCH_SM_GATE_OUT_2 PC13

//periphs
#define PIN_PATCH_SM_SPI_SCK PD10
#define PIN_PATCH_SM_SPI_CS PB4
#define PIN_PATCH_SM_SPI_MOSI PC3_C
#define PIN_PATCH_SM_SPI_MISO PC2_C

#define PIN_PATCH_SM_I2C_SCL PB8
#define PIN_PATCH_SM_I2C_SDA PB9

#define PIN_PATCH_USB_DM PB14
#define PIN_PATCH_USB_DP PB15

#define PIN_PATCH_SM_SDMMC_D3 PC11
#define PIN_PATCH_SM_SDMMC_D2 PC10
#define PIN_PATCH_SM_SDMMC_D1 PC9
#define PIN_PATCH_SM_SDMMC_D0 PC8
#define PIN_PATCH_SM_SDMMC_CLK PC12
#define PIN_PATCH_SM_SDMMC_CMD PD2

//generic names (digital)
#define PIN_PATCH_SM_A2 PA1
#define PIN_PATCH_SM_A3 PA0
#define PIN_PATCH_SM_A8 PB14
#define PIN_PATCH_SM_A9 PB15

#define PIN_PATCH_SM_B5 PC14
#define PIN_PATCH_SM_B6 PC13
#define PIN_PATCH_SM_B7 PB8
#define PIN_PATCH_SM_B8 PB9
#define PIN_PATCH_SM_B9 PG14
#define PIN_PATCH_SM_B10 PG13

#define PIN_PATCH_SM_C1 PA5
#define PIN_PATCH_SM_C2 PA7
#define PIN_PATCH_SM_C3 PA2
#define PIN_PATCH_SM_C4 PA6
#define PIN_PATCH_SM_C5 PA3
#define PIN_PATCH_SM_C6 PB1
#define PIN_PATCH_SM_C7 PC4
#define PIN_PATCH_SM_C8 PC0
#define PIN_PATCH_SM_C9 PC1
#define PIN_PATCH_SM_C10 PA4

#define PIN_PATCH_SM_D1 PB4
#define PIN_PATCH_SM_D2 PC11
#define PIN_PATCH_SM_D3 PC10
#define PIN_PATCH_SM_D4 PC9
#define PIN_PATCH_SM_D5 PC8
#define PIN_PATCH_SM_D6 PC12
#define PIN_PATCH_SM_D7 PD2
#define PIN_PATCH_SM_D8 PC2_C
#define PIN_PATCH_SM_D9 PC3_C
#define PIN_PATCH_SM_D10 PD3

#endif // variant ARDUINO_DAISY_PATCH_SM
