#ifdef ARDUINO_DAISY_PETAL_SM
#define PIN_PETAL_SM_POT_1 PIN_A1 // A3
#define PIN_PETAL_SM_POT_2 PIN_A2 // A6
#define PIN_PETAL_SM_POT_3 PIN_A3 // B1
#define PIN_PETAL_SM_POT_4 PIN_A4 // A2
#define PIN_PETAL_SM_POT_5 PIN_A5 // A7
#define PIN_PETAL_SM_POT_6 PIN_A6 // C4

#define PIN_PETAL_SM_LED_1_R 23 // A5
#define PIN_PETAL_SM_LED_1_G 13 // B6
#define PIN_PETAL_SM_LED_1_B 32 // D7
#define PIN_PETAL_SM_LED_2 33 // G14
#define PIN_PETAL_SM_LED_3_R 7 // G10
#define PIN_PETAL_SM_LED_3_G 2 // C10
#define PIN_PETAL_SM_LED_3_B 1 // C11
#define PIN_PETAL_SM_LED_4 10 // B5
#define PIN_PETAL_SM_LED_5 14 // B7

#define PIN_PETAL_SM_TOGGLE_1A 9 // B4
#define PIN_PETAL_SM_TOGGLE_1B 6 // C12
#define PIN_PETAL_SM_TOGGLE_2A 30 // B15
#define PIN_PETAL_SM_TOGGLE_2B 29 // B14
#define PIN_PETAL_SM_TOGGLE_3A 34 // A8
#define PIN_PETAL_SM_TOGGLE_3B 31 // C7

#define PIN_PETAL_SM_SWITCH_1 35 // D13
#define PIN_PETAL_SM_SWITCH_2 36 // C6

#define PIN_PETAL_SM_EXPRESSION PIN_A0 // C0

#define PIN_PETAL_SM_RELAY 37 // G13
#endif