#define PIN_POD_POT_1 A6
#define PIN_POD_POT_2 A0
#define POD_NUM_POTS 2

#define PIN_POD_SWITCH_1 27
#define PIN_POD_SWITCH_2 28
#define POD_NUM_SWITCHES 2

#define PIN_POD_LED_1_RED 20
#define PIN_POD_LED_1_GREEN 19
#define PIN_POD_LED_1_BLUE 18
#define PIN_POD_LED_2_RED 17
#define PIN_POD_LED_2_GREEN 24
#define PIN_POD_LED_2_BLUE 23
#define POD_NUM_LEDS 2

#define PIN_POD_ENC_A 26
#define PIN_POD_ENC_B 25
#define PIN_POD_ENC_CLICK 13
